crf_config:
    'filter_size': 7
    'blur': 4
    'merge': True
    'norm': 'none'
    'weight': 'vector'
    "unary_weight": 1
    "weight_init": 0.2

    'trainable': False
    'convcomp': False
    'logsoftmax': True  # use logsoftmax for numerical stability
    'softmax': True
    'final_softmax': False

    'pos_feats': {
        'sdims': 3,
        'compat': 3,
    }
    'col_feats': {
        'sdims': 80,
        'schan': 13,   # schan depend on the input scale.
                       # use schan = 13 for images in [0, 255]
                       # for normalized images in [-0.5, 0.5] try schan = 0.1
        'compat': 10,
        'use_bias': False
    }
    "trainable_bias": False

    "pyinn": False

train_config:
    data_path: 'C:\Users\zoez5\Downloads\archive'
    aux: False
    num_classes: 21
    crf: False
    fullscaleFeat: null
    held_out_images: 1
    train_with_held_out: True
    lr_scheduler: poly
    loss: CE
    device: cuda
    batch_size: 1
    epochs: 1
    lr: 1e-6
    weight_decay: 5e-4
    start_epoch: 0
    amp: False
    resume: ''
    print_freq: 100
